### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by brianmay** [lunarmodules/cgilua#16]
Different web pages have different numbers.

* https://keplerproject.github.io/cgilua/  -> 5.2
* https://github.com/keplerproject/cgilua -> 5.2.1
* https://github.com/keplerproject/cgilua/releases -> 5.2 alfa 2
* https://github.com/keplerproject/cgilua/commit/b4ea261fbce7e617a84d68ed0983cc32cccab551 -> 5.2.2
* https://github.com/keplerproject/cgilua/commit/5c4d84a586349bca8f3f3e2de5d2431c3ae7d6ec -> 6.0.1 (not sure what happened with 6.0.01).

It would be good if the official information for the project could be a little bit more consistent :-)

**Comment by tomasguisasola** [comment]
The latest version is:

http://lunarmodules.github.io/cgilua/

The other references are deprecated.
