### ISSUE TITLE
src.rock 6.0.2 missing

### ISSUE THREAD

**Issue by fperrad** [lunarmodules/cgilua#18]
@tomasguisasola  on Luarocks.org <https://luarocks.org/modules/tomasguisasola/cgilua>,
the latest version of CGILua (6.0.2) comes only with a rockspec.
Please, could you upload too the src.rock ?

The following command allows to create it :
```
    $ luarocks pack <your_rockspec>
```

**Comment by tomasguisasola** [comment]
Hi François

Please check it out again.  I think everything is fine now.

Regards,
Tomás

Em dom., 13 de dez. de 2020 às 12:05, François Perrad <
notifications@github.com> escreveu:

**Comment by fperrad** [comment]
Sorry, I don't see the missing .src.rock on https://luarocks.org/modules/tomasguisasola/cgilua/6.0.2-0

The .rockspec seems to have been updated.

**Comment by tomasguisasola** [comment]
Hi François

I uploaded it to LuaRocks site.

Regards,
Tomás

Em qua, 30 de dez de 2020 18:28, François Perrad <notifications@github.com>
escreveu:

**Comment by niecore** [comment]
Hello Tomás,

The src.rock is still missing only the rockspec is available.
Is it possible to create and upload it?

**Comment by tomasguisasola** [comment]
Hi Nico

> The src.rock is still missing only the rockspec is available.
> Is it possible to create and upload it?
Please forgive me.  I thought the .src.rock was there.  Please check
again.  I've just uploaded it.

Regards,
Tomás

**Comment by niecore** [comment]
Yes, its online now. Thank you so much :)
